name: store
description: A new Flutter application.



environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+6
  firebase_auth: ^0.11.1+1
  cloud_firestore: ^0.12.5+2
  cached_network_image: ^1.0.0
  flutter_swiper: ^1.1.6
  autocomplete_textfield: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
